### ISSUE TITLE
no_proxy settings

### ISSUE THREAD

**Issue by joeinfo35** [deralexxx/PySight2MISP#18]
How can we do no proxy setting ? Although misp is installed locally , it always goes to proxy and we have unable to connect misp. We added no_proxy= localhost, mispURL  under the proxy config but still does not work.
Thanks

**Comment by cudor** [comment]
In the configuration of the script, you can set the use_proxy variable to False.

But it seems that you are referring to environment variables. For me, the following configuration works:
Add an entry to /etc/hosts like `127.0.0.1  misp.example.org`.
Export the environment variable `no_proxy=.example.org`.

**Comment by jaegeral** [comment]
yep, what @cudor  said should work
