### ISSUE TITLE
error when running pip install

### ISSUE THREAD

**Issue by dmolina213** [deralexxx/PySight2MISP#23]
This is what i get when i run pip: I am doing anything wrong?

root@ip-172-31-24-248:/var/www/MISP/PyMISP/pymisp/isight/PySight2MISP# pip install -r requirements.txt
Collecting configparser (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting pymisp>=2.4.112 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/73/82/28b0c4ceddd2049127208c8505cfbb84dcf8c5eb29aadee4d5932546af18/pymisp-2.4.121.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yBZp6m/pymisp/setup.py", line 7, in <module>
        import pymisp
      File "pymisp/__init__.py", line 26, in <module>
        from .abstract import AbstractMISP, MISPEncode, pymisp_json_default, MISPTag, Distribution, ThreatLevel, Analysis  # noqa
      File "pymisp/abstract.py", line 46
        def _load_json(path: Path) -> Union[dict, None]:
                           ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yBZp6m/pymisp/

**Comment by jaegeral** [comment]
Hm, that seems to be a pymisp install issue. can you try to do
> pip install pymisp

**Comment by dmolina213** [comment]
Thanks I got it working.

V/R
Help Me, Help You
Douglas P Molina, MBA, CISSP, C|EH, CySA+,CCSK,GCTI
U.S. Department of Veterans Affairs
Office of Information Security (OIS)
Cyber Threat Intelligence (CTI)
Work Phone: 708-938-2720
Mobile Phone: 202 779 2034
UNCLASS: douglas.molina@va.gov<mailto:douglas.molina@va.gov>
[cid:image001.jpg@01D61BE5.04BA0950]

**Comment by dmolina213** [comment]
How do I make this as a scheduled pull? would it be by running a cron job on which py program? Also will the data retrieved be written automatically to an event which can be viewed on the MISP GUI? 

I am not a python developer by trade so i am learning on the fly.

**Comment by jaegeral** [comment]
Yes, cron would be the way to go, it would be good if you would open new issues as they come along :-)

**Comment by dmolina213** [comment]
yes, I have a lot of questions forming as I try to unpack this.
Does the information makes its way into the MISP GUI and how ?
